version: "3.8"

services:
  pds-takehome:
    build: .
    container_name: pds-takehome-app
    stdin_open: true # Keep stdin open
    tty: true # Allocate a TTY
    ports:
      - "5000:80"
    environment:
      - DOTNET_ENVIRONMENT=Development
